### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Manchuker1120** [CheckPointSW/ExportImportPolicyPackage#102]
python import_export_package.py -op export --name "WG2-QZ-FW-POLICY" --all true -u admin -p "Sx[00]Wg(00)" -m 10.140.197.240 --force true
None
Traceback (most recent call last):
  File "/app/netdevops/ExportImportPolicyPackage-master/import_export_package.py", line 30, in <module>
    args = process_arguments(arg_parser)
  File "/app/netdevops/ExportImportPolicyPackage-master/utils.py", line 103, in process_arguments
    args = Menu(args).self_args
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 21, in __init__
    self.build()
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 148, in build
    self.build()
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 148, in build
    self.build()
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 148, in build
    self.build()
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 146, in build
    self.display()
  File "/app/netdevops/ExportImportPolicyPackage-master/menu.py", line 25, in display
    for i in range(1, len(self.options)):
TypeError: object of type 'NoneType' has no len()

**Comment by chkp-edenbr** [comment]
Hi @Manchuker1120 
Seems to be an issue with the 'force' parameter.
A fix will be added to the next release.
Thanks,
Eden

**Comment by chkp-edenbr** [comment]
Issue fixed in new release v6.2.0
