### ISSUE TITLE
ERROR: Failed to handle asynchronous tasks as synchronous, tasks result is undefined

### ISSUE THREAD

**Issue by manuadoor** [CheckPointSW/ExportImportPolicyPackage#30]
Policy Package Import failed to a Domain in R80.10 MDS - following is the error (in italics)  happens after importing access-sections -

`
_Imported 80 out of 114 access-sections (70%)

Imported 100 out of 114 access-sections (87%)

Traceback (most recent call last):
  File "import_export_package.py", line 61, in <module>
    import_package(client, args)
  File "/Users/user/Desktop/cpmigration/ExportImportPolicyPackage-master/importing/import_package.py", line 52, in import_package
    layers_to_attach = import_objects(args.file, client, {})
  File "/Users/user/Desktop/cpmigration/ExportImportPolicyPackage-master/importing/import_objects.py", line 103, in import_objects
    import_objects(rulebase_object_file.name, client, changed_layer_names, layer_name)
  File "/Users/user/Desktop/cpmigration/ExportImportPolicyPackage-master/importing/import_objects.py", line 94, in import_objects
    changed_layer_names, api_call, num_objects, client)
  File "/Users/user/Desktop/cpmigration/ExportImportPolicyPackage-master/importing/import_objects.py", line 335, in add_object
    publish_reply = client.api_call("publish", wait_for_task=True)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/cpapi/mgmt_api.py", line 352, in api_call
    res = self.__wait_for_task(res.data["task-id"])
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/cpapi/mgmt_api.py", line 510, in __wait_for_task
    task_result)
cpapi.api_exceptions.APIException: ERROR: Failed to handle asynchronous tasks as synchronous, tasks result is undefined_
`

**Comment by chkp-royl** [comment]
Hi @manuadoor,
It seems to be related to our Python SDK and not the tool itself.
In order to investigate this issue, please send the exported file (tar.gz) you try import + tool logs + specify from which version you did export to royl@checkpoint.com.

Thanks,
Roy

**Comment by manuadoor** [comment]
Hello @chkp-royl  Thanks for responding. This issue was further isolated due to compute resources, allocating more resources solved this....

Thanks....
