### ISSUE TITLE
Unable to export policy R81 - Policy not found

### ISSUE THREAD

**Issue by ramma83** [CheckPointSW/ExportImportPolicyPackage#56]
Process prior to issue:

Existing R80.20 VM:
1. run a migrate export

Created new R80.20 VM:
2. imported the policy from Step 1 above.
3. Tested export of policy using import_export tool - success
3. Upgraded VM to R81 JHF T36
4. Attempted to export an existing package "DMZ-FW-POLICY":

```
[Expert@check_point_mng:0]# mgmt_cli -r true show packages
packages: 
- uid: "20c1a0d6-2136-4b68-a292-045efe5be989"
  name: "**_DMZ-FW-POLICY_**"
  type: "package"
  domain: 
    uid: "41e821a0-3720-11e3-aa6e-0800200c9fde"
    name: "SMC User"
    domain-type: "domain"
  icon: "Blades/Access"
  color: "black"
- uid: "8c0e10a6-fad7-4238-ae58-6d70fe6d3150"
  name: "FW-2200-POLICY"
  type: "package"
  domain: 
    uid: "41e821a0-3720-11e3-aa6e-0800200c9fde"
    name: "SMC User"
    domain-type: "domain"
  icon: "Blades/Access"
  color: "black"
- uid: "4ac80585-e138-43dd-8680-34a00b8cf262"
  name: "FW-4600-POLICY"
  type: "package"
  domain: 
    uid: "41e821a0-3720-11e3-aa6e-0800200c9fde"
    name: "SMC User"
    domain-type: "domain"
  icon: "Blades/Access"
  color: "black"
- uid: "2214aa5e-264e-410f-92ac-3587cbce4b46"
  name: "Merged-Policy"
  type: "package"
  domain: 
    uid: "41e821a0-3720-11e3-aa6e-0800200c9fde"
    name: "SMC User"
    domain-type: "domain"
  icon: "Blades/Access"
  color: "black"
from: 1
to: 4
total: 4

[Expert@check_point_mng:0]# /opt/CPsuite-R81/fw1/Python/bin/python3.7 /home/admin/ExportImportPolicyPackage-master/import_export_package.py

Welcome to the Policy Package Import/Export Tool.
What would you like to do?
1. Import a package
2. Export a package
99. Exit
2
Please enter a Policy Package name to export:
DMZ-FW-POLICY
Please select a login method:
1. Enter user credentials manually
2. Login as Root
3. Use an existing session file
4. Use an existing session UID
99. Back
2
The script will run with the following parameters:
Export Access-Control layers = True
Export NAT layers = True
Export Threat-Prevention layers = True
Export HTTPS Inspection layers = True
Output-file name = None
Management Server IP = 127.0.0.1
Management Server Port = 443
Management Server Domain = None
1. Change Settings
2. Run
99. Back
2
You currently do not have a record of this server's fingerprint.
Server's fingerprint: F6A5B69661ACA067CFE159FD6282D41137D9FBE3
Do you accept this fingerprint? [y/n] y
Fingerprint saved.

No package named 'DMZ-FW-POLICY' found. Cannot export.
```

5. Attempted to export a different policy: "Merged Policy" however an error occurred after retrieving the Access Layer:

```
[Expert@check_point_mng:0]# /opt/CPsuite-R81/fw1/Python/bin/python3.7 /home/admin/ExportImportPolicyPackage-master/import_export_package.py

Welcome to the Policy Package Import/Export Tool.
What would you like to do?
1. Import a package
2. Export a package
99. Exit
2
Please enter a Policy Package name to export:
Merged-Policy   
Please select a login method:
1. Enter user credentials manually
2. Login as Root
3. Use an existing session file
4. Use an existing session UID
99. Back
2
The script will run with the following parameters:
Export Access-Control layers = True
Export NAT layers = True
Export Threat-Prevention layers = True
Export HTTPS Inspection layers = True
Output-file name = None
Management Server IP = 127.0.0.1
Management Server Port = 443
Management Server Domain = None
1. Change Settings
2. Run
99. Back
2
Exporting Access Control layers

Exporting Access Layer [Merged-Policy Security]

Retrieved 50 out of 532 rules (9%)

Retrieved 100 out of 532 rules (18%)

Retrieved 150 out of 532 rules (28%)

Retrieved 200 out of 532 rules (37%)

Retrieved 250 out of 532 rules (46%)

Retrieved 300 out of 532 rules (56%)

Retrieved 350 out of 532 rules (65%)

Retrieved 400 out of 532 rules (75%)

Retrieved 450 out of 532 rules (84%)

Retrieved 500 out of 532 rules (93%)

Retrieved 532 out of 532 rules (100%)

Traceback (most recent call last):
  File "/home/admin/ExportImportPolicyPackage-master/import_export_package.py", line 61, in <module>
    export_package(client, args)
  File "/home/admin/ExportImportPolicyPackage-master/exporting/export_package.py", line 44, in export_package
    = export_access_rulebase(show_package.data["name"], access_layer["name"], access_layer["uid"], client, timestamp, tar_file)
  File "/home/admin/ExportImportPolicyPackage-master/exporting/export_access_rulebase.py", line 16, in export_access_rulebase
    get_query_rulebase_data(client, "access-rulebase", {"name": layer, "uid": layer_uid, "package": package})
  File "/home/admin/ExportImportPolicyPackage-master/exporting/export_objects.py", line 115, in get_query_rulebase_data
    check_for_export_error(general_object, client)
  File "/home/admin/ExportImportPolicyPackage-master/utils.py", line 465, in check_for_export_error
    general_object["type"] not in singular_to_plural_dictionary[client.api_version]):
KeyError: '1.7.1'
```

**Comment by brattip** [comment]
same problem from R81

```
Exporting Access Control layers

Exporting Access Layer [test Network]

Retrieved 10 out of 10 rules (100%)

Traceback (most recent call last):
  File "C:\Users\aaa\Desktop\aaa\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master\import_export_package.py", line 61, in <module>
    export_package(client, args)
  File "C:\Users\aaa\Desktop\aaa\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master\exporting\export_package.py", line 44, in export_package
    = export_access_rulebase(show_package.data["name"], access_layer["name"], access_layer["uid"], client, timestamp, tar_file)
  File "C:\Users\aaa\Desktop\aaa\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master\exporting\export_access_rulebase.py", line 16, in export_access_rulebase
    get_query_rulebase_data(client, "access-rulebase", {"name": layer, "uid": layer_uid, "package": package})
  File "C:\Users\aaa\Desktop\aaa\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master\exporting\export_objects.py", line 115, in get_query_rulebase_data
    check_for_export_error(general_object, client)
  File "C:\Users\aaa\Desktop\aaa\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master\utils.py", line 465, in check_for_export_error
    general_object["type"] not in singular_to_plural_dictionary[client.api_version]):
KeyError: '1.7.1'
```
