### ISSUE TITLE
Error importing Updatable-Objects - R81.10

### ISSUE THREAD

**Issue by mpoben** [CheckPointSW/ExportImportPolicyPackage#70]
Traceback (most recent call last):
  File "import_export_package.py", line 67, in <module>
    import_package(client, args)
  File "/home/admin/ExportImportPolicyPackage-5.5/importing/import_package.py", line 56, in import_package
    layers_to_attach = import_objects(args.file, client, {}, package, None, args)
  File "/home/admin/ExportImportPolicyPackage-5.5/importing/import_objects.py", line 198, in import_objects
    changed_layer_names, api_call, num_objects, client, args, package)
  File "/home/admin/ExportImportPolicyPackage-5.5/importing/import_objects.py", line 413, in add_object
    debug_log("Failed to update updatable objects repository \"%s\"" % updatable_objects_repository_reply.error_message, True, True)
AttributeError: 'APIResponse' object has no attribute 'error_message'

**Comment by chkp-edenbr** [comment]
Hi,
Thank you for pointing out this issue.
We found the bug and it will be fixed in the next version of the tool.
Thanks,
Eden

**Comment by chkp-edenbr** [comment]
Hi,
The bug is fixed in our latest version v5.6
