### ISSUE TITLE
problem while exporting to tar file

### ISSUE THREAD

**Issue by quabank** [CheckPointSW/ExportImportPolicyPackage#74]
Done exporting layer 'ABC_Policy Security'.

Hi Eden!
I tried changed new device and install new python's environment. But it still show these problems. Can you expain these problem and any suggestions to fix it.
Thanks.

Traceback (most recent call last):
  File "D:\ExportImportPolicyPackage-master\import_export_package.py", line 65, in <module>
    export_package(client, args)
  File "D:\ExportImportPolicyPackage-master\exporting\export_package.py", line 54, in export_package
  File "D:\ExportImportPolicyPackage-master\\utils.py", line 289, in write_data
    writer.writerows(res)
  File "C:\Users\AppData\Local\Programs\Python39\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ec3' in position 87: character maps to <undefined>
PS C:\Users\Desktop\ExportImportPolicyPackage-master (1)\ExportImportPolicyPackage-master>

**Comment by quabank** [comment]
and could you sent me your python version and environment you are using. I think the problem still from environment.
Thanks Eden

**Comment by chkp-edenbr** [comment]
Hi @quabank 
From version 5.0 the tool is developed using Python language version 3.7
Also, you should set the file encoding to use UTF-8

**Comment by quabank** [comment]
> Hi @quabank From version 5.0 the tool is developed using Python language version 3.7 Also, you should set the file encoding to use UTF-8

Thanks for reply. My python version: 3.9 . I set the file encoding and its worked. So i import this policy and there some problems after done importing object.  
Thanks

Traceback (most recent call last):


  File "c:\Users\Desktop\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master - Copy\import_export_package.py", line 67, in <module>
    import_package(client, args)
  File "c:\Users\Desktop\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master - Copy\importing\import_package.py", line 56, in import_package
    layers_to_attach = import_objects(args.file, client, {}, package, None, args)
  File "c:\Users\Desktop\ExportImportPolicyPackage-master\ExportImportPolicyPackage-master - Copy\importing\import_objects.py", line 115, in import_objects
    os.remove(general_object_file.name)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '03____add-host__2022_07_11_13_40.json'

**Comment by quabank** [comment]
@chkp-edenbr may you check this
